In [1]:
import numpy as np


In [34]:
import math as m

In [2]:
A = np.array([[1,2,3],  [4,5,6],  [7,8,9]])
B = np.array([[4,5,4],  [2,3,8],  [6,2,5]])

In [17]:
print (A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
print(B)

[[4 5 4]
 [2 3 8]
 [6 2 5]]


In [5]:
tran= (A + B).T

In [6]:
print (tran)

[[ 5  6 13]
 [ 7  8 10]
 [ 7 14 14]]


In [26]:
X = np.all((A @ B).T==A.T @ B.T)

In [12]:
y = tran.T

In [27]:
print (X)

False


In [13]:
sym = (tran + y)/2

In [14]:
print(sym)

[[ 5.   6.5 10. ]
 [ 6.5  8.  12. ]
 [10.  12.  14. ]]


In [15]:
c=np.dot(A,B)

In [16]:
print(c)

[[ 26  17  35]
 [ 62  47  86]
 [ 98  77 137]]


In [19]:
v= np.cross(A,B)

In [20]:
print(v)

[[ -7   8  -3]
 [ 22 -20   2]
 [ 22  19 -34]]


In [30]:
E= np.linalg.det(A)

In [31]:
print(E)

0.0


In [32]:
U= np.linalg.inv(B)
print(U)

[[-0.00769231 -0.13076923  0.21538462]
 [ 0.29230769 -0.03076923 -0.18461538]
 [-0.10769231  0.16923077  0.01538462]]


In [63]:
def create_symmetric (n):
  mat=np.zeros((n,n),dtype=int)
  for i in range(n):
    for j in range(i,n):
      val = np.random.randint(4,17)
      mat[i][j] = val
      mat[j][i]= val
    return mat

In [66]:
symmetric(2)

array([[ 5, 11],
       [11,  0]])

In [43]:
F = np.array([1,7,4,3,8,4,7,3,9,2,6,9,1,5,7,6])
S=np.count_nonzero(F<8)
print(S)

13
